// CoreVueTypeScript/ClientApp/src/components/navmenu/navmenu.vue
<template>
  <div>
    <nav class="nav collapse flex-column nav-pills" id="route-nav-bar" role="tablist">
      <div class="bg-dark p-4">
        <router-link to="/" :exact="true">
          <span class="nav-link nav-link-item" data-toggle="pill">Home</span>
        </router-link>
        <router-link to="/counter">
          <span class="nav-link nav-link-item" data-toggle="pill">Counter</span>
        </router-link>
        <router-link to="/fetchdata">
          <span class="nav-link nav-link-item" data-toggle="pill">Fetch data</span>
        </router-link>
      </div>
    </nav>
    <nav class="justify-content-between navbar navbar-dark bg-dark">
      <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#route-nav-bar" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <router-link to="/">
        <span class="navbar-brand">Vue</span>
      </router-link>
    </nav>
  </div>
</template>

<style src="./navmenu.css">

// CoreReactReduxTypeScript/ClientApp/components/NavMenu.tsx
import * as React from 'react';
import { NavLink, Link } from 'react-router-dom';

export class NavMenu extends React.Component<{}, {}> {
    public render() {
        return <div className='main-nav'>
                <div className='navbar navbar-inverse'>
                <div className='navbar-header'>
                    <button type='button' className='navbar-toggle' data-toggle='collapse' data-target='.navbar-collapse'>
                        <span className='sr-only'>Toggle navigation</span>
                        <span className='icon-bar'></span>
                        <span className='icon-bar'></span>
                        <span className='icon-bar'></span>
                    </button>
                    <Link className='navbar-brand' to={ '/' }>CoreReactReduxTypeScript</Link>
                </div>
                <div className='clearfix'></div>
                <div className='navbar-collapse collapse'>
                    <ul className='nav navbar-nav'>
                        <li>
                            <NavLink exact to={ '/' } activeClassName='active'>
                                <span className='glyphicon glyphicon-home'></span> Home
                            </NavLink>
                        </li>
                        <li>
                            <NavLink to={ '/Comp2' } activeClassName='active'>
                                <span className='glyphicon glyphicon-home'></span> Comp2
                            </NavLink>
                        </li>
                        <li>
                            <NavLink to={ '/Counter' } activeClassName='active'>
                                <span className='glyphicon glyphicon-home'></span> Counter
                            </NavLink>
                        </li>
                    </ul>
                </div>
            </div>
        </div>;
    }
}
